### ISSUE TITLE
[RFE] Search for "rubygem-foo"

### ISSUE THREAD

**Issue by voxik** [zuhao/isitfedoraruby#4]
Would be nice if the search would search for "rubygem-foo" as well as just "foo". Thank you

**Comment by zuhao** [comment]
Thanks for the suggestion! I've made the change. It should be reflected when @movitto makes the deployment.

**Comment by voxik** [comment]
Thank you!

**Comment by movitto** [comment]
Hey will try to push a new update to the site twice a month, or once every other week. Though this may sometimes get shifted around a little bit due to other priorities.

I've been running the update task manually on every update, am still a little apprehensive about adding it to a cron job. Want to tweak / improve the performance of the import operation a little bit more and make sure we handle all edge cases before doing that. Will look at this in the near future unless someone gets to it first
